Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/iden_1D/testmixnet.py", line 136, in <module>
    hist_data = testnet(name_group)
  File "/home/zerui603/MDN_lc_iden/iden_1D/testmixnet.py", line 130, in testnet
    return np.array([np.histogram( lgdchis_act0, range=hist_bins_axis),np.histogram( lgdchis_act1, range=hist_bins_axis),np.histogram( lgdchis_pre0, range=hist_bins_axis),np.histogram( lgdchis_pre1, range=hist_bins_axis)])
  File "<__array_function__ internals>", line 6, in histogram
  File "/home/zerui603/.local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 795, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/home/zerui603/.local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 429, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/home/zerui603/.local/lib/python3.7/site-packages/numpy/lib/histograms.py", line 313, in _get_outer_edges
    first_edge, last_edge = range
ValueError: too many values to unpack (expected 2)
