Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 198, in <module>
    training(paramsid=0)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 130, in training
    loss = criterion(outputs,labels)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 1152, in forward
    label_smoothing=self.label_smoothing)
  File "/home/zerui603/.conda/envs/PytorchCd11/lib/python3.7/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected target size [10000, 1000], got [10000, 500]
